config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filterselect.urls')),
]

core/urls.py
from django.urls import path
from . import views as v

app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
    path('districts/choices/ajax/', v.districts_choices_ajax, name='districts_choices_ajax'),
]

"""
urlpatterns = [
    path('', v.index, name='index'),
    path('person/json/', v.person_json, name='person_json'),
    path('filter_list/', v.filter_list, name='filter_list'),
    path('filter_dropdown/', v.filter_dropdown, name='filter_dropdown'),
    path('filter_dropdown2/', v.filter_dropdown2, name='filter_dropdown2'),
    path('cities/ajax/', v.cities_ajax, name='cities_ajax'),
    path('cities/choices/ajax/', v.cities_choices_ajax, name='cities_choices_ajax'),
    path('districts/ajax/', v.districts_ajax, name='districts_ajax'),
    path('districts/choices/ajax/', v.districts_choices_ajax, name='districts_choices_ajax'),
]
"""

filterlist/urls.py
from django.urls import path
from . import views

app_name = 'filterlist'

urlpatterns = [
    path('', views.filter, name='filter'),
    path('country/choices/ajax/', views.country_choices_ajax, name='country_choices_ajax'),
    path('state/choices/ajax/', views.state_choices_ajax, name='state_choices_ajax'),
    path('city/choices/ajax/', views.city_choices_ajax, name='city_choices_ajax'),
    path('filter_result/<int:uf>/', views.filter_result, name='filter_result'),
]

filterlist/models.py
from django.db import models


class Country(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = 'country'
        verbose_name_plural = 'countries'


class State(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = 'state'
        verbose_name_plural = 'states'


class City(models.Model):
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = 'city'
        verbose_name_plural = 'cities'

core/forms.py
from django import forms
from localflavor.br.br_states import STATE_CHOICES
from .models import City, District


class StateForm(forms.Form):
    state = forms.ChoiceField(
        choices=STATE_CHOICES,
        label='Estado',
        # widget=forms.Select(
        #     attrs={'class': 'form-control'}
        # )
    )
    city = forms.ModelChoiceField(
        queryset=City.objects.none(),
        required=False
    )
    district = forms.ModelChoiceField(
        queryset=District.objects.none(),
        required=False
    )

    class Meta:
        fields = ('state', 'city', 'district')

    def __init__(self, state=None, city=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.filter(uf=state)
        if city:
            self.fields['district'].queryset = District.objects.filter(
                city=city)

filterlist/views.py
from django.http import HttpResponse
from django.shortcuts import render

from .models import City, Country, State


def filter(request):
    context = {}
    context['country'] = Country.objects.all()
    context['state'] = State.objects.none
    context['city'] = City.objects.none
    return render(request, 'filter.html', context)


def filter_result(request, uf):
    return HttpResponse('Resultado del filtro valor={}'.format(uf))


def country_choices_ajax(request):
    data = Country.objects.all()
    context = {'countries': data}
    return render(request, 'includes/country_choices.html', context)


def state_choices_ajax(request):
    countryId = request.GET['uf']
    countryOb = Country.objects.get(id=countryId)
    data = State.objects.filter(country=countryOb)
    context = {'states': data}
    return render(request, 'includes/state_choices.html', context)


def city_choices_ajax(request):
    stateId = request.GET['uf']
    stateOb = State.objects.get(id=stateId)
    data = City.objects.filter(state=stateOb)
    context = {'cities': data}
    return render(request, 'includes/city_choices.html', context)

filterlist/templates/filter.html
{% extends "layout/base.html" %}
{% load static %}

{% block content %}
<div class="jumbotron">
    <div class="container">
        <h2>Ejemplo de uso de listas dependientes</h2>
        <p><i>La primera lista filtra el contenido de la siguiente.</i></p>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col">
            <div class="countries">
                <h5>Países</h5>
                <div id="id_country"></div>
            </div>
        </div>
        <div class="col">
            <div class="states">
                <h5>Estados</h5>
                <div id="id_state"></div>
            </div>
        </div>
        <div class="col">
            <div class="cities">
                <h5>Provincias</h5>
                <div id="id_city"></div>
            </div>
        </div>
    </div>
</div>
<hr>
{% endblock content %}

{% block js %}
<script>
$(document).ready(function() {
    let urlPath = '{% url 'filterlist:country_choices_ajax' %}';
    $.ajax({
        url: urlPath,
        success: function(response) {
            $('#id_country').html(response);
        }
    })
    event.preventDefault();
});

$(document).on('click', '.country', function(event) {
    let url = $(this).data('url');
    let uf = $(this).data('uf');

    $.ajax({
        url: url,
        data: {uf: uf},
        success: function(response) {
            $('#id_state').html(response);
        }
    })
    event.preventDefault();
});

$(document).on('click', '.state', function(event) {
    let url = $(this).data('url');
    let uf = $(this).data('uf');

    $.ajax({
        url: url,
        data: {uf: uf},
        success: function(response) {
            $('#id_city').html(response);
        }
    })
    event.preventDefault();
});
</script>
{% endblock js %}