config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filterselect.urls')),
]

core/urls.py
from django.urls import path
from . import views as v

app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
    path('districts/choices/ajax/', v.districts_choices_ajax, name='districts_choices_ajax'),
]

"""
urlpatterns = [
    path('', v.index, name='index'),
    path('person/json/', v.person_json, name='person_json'),
    path('filter_list/', v.filter_list, name='filter_list'),
    path('filter_dropdown/', v.filter_dropdown, name='filter_dropdown'),
    path('filter_dropdown2/', v.filter_dropdown2, name='filter_dropdown2'),
    path('cities/ajax/', v.cities_ajax, name='cities_ajax'),
    path('cities/choices/ajax/', v.cities_choices_ajax, name='cities_choices_ajax'),
    path('districts/ajax/', v.districts_ajax, name='districts_ajax'),
    path('districts/choices/ajax/', v.districts_choices_ajax, name='districts_choices_ajax'),
]
"""

filterselect/urls.py
from django.urls import path
from . import views

app_name = 'filterselect'

urlpatterns = [
    path('', views.filter, name='filter'),
    path('country/choices/ajax/', views.country_choices_ajax, name='country_choices_ajax'),
    path('state/choices/ajax/', views.state_choices_ajax, name='state_choices_ajax'),
    path('city/choices/ajax/', views.city_choices_ajax, name='city_choices_ajax'),
    path('filter_result/', views.filter_result, name='filter_result'),
]

filterselect/models.py
from django.db import models


class Country(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = 'country'
        verbose_name_plural = 'countries'


class State(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = 'state'
        verbose_name_plural = 'states'


class City(models.Model):
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = 'city'
        verbose_name_plural = 'cities'

filterselect/views.py
from django.http import HttpResponse
from django.shortcuts import render

from .models import City, Country, State


def filter(request):
    context = {}
    context['country'] = Country.objects.all()
    context['state'] = State.objects.none
    context['city'] = City.objects.none
    return render(request, 'filter.html', context)


def filter_result(request):
    data = Country.objects.all()
    context = {'dataset': data}
    return render(request, 'includes/table_result.html', context)


def country_choices_ajax(request):
    data = Country.objects.all()
    context = {'countries': data}
    return render(request, 'includes/country_choices.html', context)


def state_choices_ajax(request):
    countryId = request.GET['uf']
    countryOb = Country.objects.get(id=countryId)
    data = State.objects.filter(country=countryOb)
    context = {'states': data}
    return render(request, 'includes/state_choices.html', context)


def city_choices_ajax(request):
    stateId = request.GET['uf']
    stateOb = State.objects.get(id=stateId)
    data = City.objects.filter(state=stateOb)
    context = {'cities': data}
    return render(request, 'includes/city_choices.html', context)

filterselect/templates/filter.html
{% extends "layout/base.html" %}
{% load static %}

{% block content %}
<div class="jumbotron">
    <div class="container">
        <h2>Ejemplo de uso de drilldown dependientes</h2>
        <p><i>El primer drilldown filtra el contenido del siguiente.</i></p>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col">
            {% include 'table_result.html' %}
        </div>
        <div class="col-md-3" style="background-color: #e9ecef;">
            {% include 'form_select.html' %}
        </div>
    </div>
</div>
<hr>
{% endblock content %}

{% block js %}
<script>
    $(document).ready(function() {
        let urlPath = '{% url 'filterselect:country_choices_ajax' %}';
        $.ajax({
            url: urlPath,
            success: function(response) {
                $('#countrySelect').html(response);
            }
        })
        event.preventDefault();
    });

    $('#countrySelect').change(function() {
        let urlPath = '{% url 'filterselect:state_choices_ajax' %}';
        let ufId = $(this).val();

        $.ajax({
            url: urlPath,
            data: {uf: ufId},
            success: function(response) {
                $('#stateSelect').html(response);
                $('#citySelect').html('<option value="">---------------------</option>');
            }
        })
    });

    $('#stateSelect').change(function() {
        let urlPath = '{% url 'filterselect:city_choices_ajax' %}';
        let ufId = $(this).val();

        $.ajax({
            url: urlPath,
            data: {uf: ufId},
            success: function(response) {
                $('#citySelect').html(response);
            }
        })
    });

    $(document).on('click', '.btn', function(event) {
        let urlPath = '{% url 'filterselect:filter_result' %}';
        let ufId = 999;

        $.ajax({
            url: urlPath,
            dataType: "HTML",
            data: {uf: ufId},
            success: function(response) {
                $("#tableResult tbody").empty();
                $('#tableResult tbody').append(response);
            }
        })
        event.preventDefault();
        alert('ok');
    });

</script>
{% endblock js %}

filterselect/templates/form_select.html
<div class="form-group">
    <label for="stateSelect">País</label>
    <select class="form-control" id="countrySelect" name="country">
        <option>---------------------</option>
    </select>
</div>
<div class="form-group" style="padding:10px;">
    <label for="stateSelect">Provincia</label>
    <select class="form-control" id="stateSelect" name="state">
        <option>---------------------</option>
    </select>
</div>
<div class="form-group" style="padding:10px;">
    <label for="citySelect">Ciudad</label>
    <select class="form-control" id="citySelect" name="city">
        <option>---------------------</option>
    </select>
</div>
<div class="form-group">
    <button class="btn btn-success pull-right" type="submit">Aplicar</button>
    <!-- <a href="" class="result btn btn-success">Aplicar</a> -->
</div>

filterselect/templates/table_result.html
<table class="table" id="tableResult">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Telefono</th>
            <th>UF</th>
        </tr>
    </thead>
    <tbody name="dataset">
        <tr>
            <td>Roberto</td>
            <td>West</td>
            <td>12345678</td>
            <td>99</td>
        </tr>
        {% for person in persons %}
        <tr>
            <td>{{ person.name }}</td>
            <td>{{ person.lastname }}</td>
            <td>{{ person.phone }}</td>
            <td>{{ person.id }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>